version: '3.4'

networks:
  api_network:
   driver: bridge

  #web_network:
  # driver: bridge

services:
  dboperationapp:
     container_name: db-operation-app
     image: mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04
     ports:
       - 5061:1433
     environment:
       - ACCEPT_EULA=Y
       - MSSQL_SA_PASSWORD=yourStrong(!)Password
     networks:
       - api_network

  webapidboperations:
    container_name: web-api-app
    image: shashikantshah951/webapidboperations:v1.0
    build:
      context: .
      dockerfile: WebAPIDBOperations/Dockerfile
    ports:
       - 8750:80
       - 8443:443
    depends_on:
       - dboperationapp
    environment:
       - DB_HOST=dboperationapp
       - DB_NAME=apidbname
       - DB_SA_PASSWORD=yourStrong(!)Password
    networks:
       - api_network

  #webapp:
  #  container_name: web-app
  #  image: ${DOCKER_REGISTRY-}webapp:v1.0
  #  build:
  #    context: .
  #    dockerfile: WebApp/Dockerfile
  #  ports:
  #     - 7050:80
  #     - 7043:443
  #  depends_on:
  #     - webapidboperations
  #  networks:
  #     - web_network

